#define R_NO_REMAP
#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

/* generated by data-raw/make_callentries.R */
extern SEXP arch_c_array_from_sexp(SEXP buffers_sexp, SEXP length_sexp, SEXP null_count_sexp, SEXP int64_sexp, SEXP children_sexp, SEXP dictionary_xptr);
extern SEXP arch_c_array_info(SEXP array_data_xptr);
extern SEXP arch_c_arch_array_stream(SEXP array_list, SEXP schema_xptr);
extern SEXP arch_c_function_array_stream(SEXP schema_xptr, SEXP call, SEXP env);
extern SEXP arch_c_export_array_stream(SEXP parent_array_stream_xptr, SEXP xptr_dst);
extern SEXP arch_c_arch_array_stream_get_schema(SEXP array_stream_xptr);
extern SEXP arch_c_arch_array_stream_get_next(SEXP array_stream_xptr);
extern SEXP arch_c_array_validate(SEXP array_sexp);
extern SEXP arch_c_logical_from_bitmask(SEXP bitmask, SEXP start_sexp, SEXP end_sexp);
extern SEXP arch_c_bitmask_from_logical(SEXP lgl_sexp);
extern SEXP arch_c_logical_from_array(SEXP array_sexp);
extern SEXP arch_c_integer_from_array(SEXP array_sexp);
extern SEXP arch_c_double_from_array(SEXP array_sexp);
extern SEXP arch_c_raw_from_array(SEXP array_sexp);
extern SEXP arch_c_character_from_array(SEXP array_sexp);
extern SEXP arch_c_buffers_from_character(SEXP chr);
extern SEXP arch_c_deep_copy(SEXP array_sexp);
extern SEXP arch_c_double_from_int64(SEXP value, SEXP start_sexp, SEXP end_sexp);
extern SEXP arch_c_int64_from_double(SEXP dbl_sexp);
extern SEXP arch_c_int64_from_integer(SEXP int_sexp);
extern SEXP arch_c_pointer(SEXP obj_sexp);
extern SEXP arch_c_pointer_is_valid(SEXP ptr);
extern SEXP arch_c_pointer_release(SEXP ptr);
extern SEXP arch_c_pointer_addr_dbl(SEXP ptr);
extern SEXP arch_c_pointer_addr_chr(SEXP ptr);
extern SEXP arch_c_pointer_move(SEXP ptr_src, SEXP ptr_dst);
extern SEXP arch_c_export_schema(SEXP schema_xptr, SEXP ptr_dst);
extern SEXP arch_c_export_array_data(SEXP array_data_xptr, SEXP ptr_dst);
extern SEXP arch_c_allocate_schema();
extern SEXP arch_c_allocate_array_data();
extern SEXP arch_c_allocate_array_stream();
extern SEXP arch_c_schema_xptr_new(SEXP format_sexp, SEXP name_sexp, SEXP metadata_sexp, SEXP flags_sexp, SEXP children_sexp, SEXP dictionary_xptr);
extern SEXP arch_c_schema_deep_copy(SEXP schema_xptr);
extern SEXP arch_c_schema_data(SEXP schema_xptr);
extern SEXP arch_c_xptr_addr(SEXP xptr);

static const R_CallMethodDef CallEntries[] = {
  {"arch_c_array_from_sexp", (DL_FUNC) &arch_c_array_from_sexp, 6},
  {"arch_c_array_info", (DL_FUNC) &arch_c_array_info, 1},
  {"arch_c_arch_array_stream", (DL_FUNC) &arch_c_arch_array_stream, 2},
  {"arch_c_function_array_stream", (DL_FUNC) &arch_c_function_array_stream, 3},
  {"arch_c_export_array_stream", (DL_FUNC) &arch_c_export_array_stream, 2},
  {"arch_c_arch_array_stream_get_schema", (DL_FUNC) &arch_c_arch_array_stream_get_schema, 1},
  {"arch_c_arch_array_stream_get_next", (DL_FUNC) &arch_c_arch_array_stream_get_next, 1},
  {"arch_c_array_validate", (DL_FUNC) &arch_c_array_validate, 1},
  {"arch_c_logical_from_bitmask", (DL_FUNC) &arch_c_logical_from_bitmask, 3},
  {"arch_c_bitmask_from_logical", (DL_FUNC) &arch_c_bitmask_from_logical, 1},
  {"arch_c_logical_from_array", (DL_FUNC) &arch_c_logical_from_array, 1},
  {"arch_c_integer_from_array", (DL_FUNC) &arch_c_integer_from_array, 1},
  {"arch_c_double_from_array", (DL_FUNC) &arch_c_double_from_array, 1},
  {"arch_c_raw_from_array", (DL_FUNC) &arch_c_raw_from_array, 1},
  {"arch_c_character_from_array", (DL_FUNC) &arch_c_character_from_array, 1},
  {"arch_c_buffers_from_character", (DL_FUNC) &arch_c_buffers_from_character, 1},
  {"arch_c_deep_copy", (DL_FUNC) &arch_c_deep_copy, 1},
  {"arch_c_double_from_int64", (DL_FUNC) &arch_c_double_from_int64, 3},
  {"arch_c_int64_from_double", (DL_FUNC) &arch_c_int64_from_double, 1},
  {"arch_c_int64_from_integer", (DL_FUNC) &arch_c_int64_from_integer, 1},
  {"arch_c_pointer", (DL_FUNC) &arch_c_pointer, 1},
  {"arch_c_pointer_is_valid", (DL_FUNC) &arch_c_pointer_is_valid, 1},
  {"arch_c_pointer_release", (DL_FUNC) &arch_c_pointer_release, 1},
  {"arch_c_pointer_addr_dbl", (DL_FUNC) &arch_c_pointer_addr_dbl, 1},
  {"arch_c_pointer_addr_chr", (DL_FUNC) &arch_c_pointer_addr_chr, 1},
  {"arch_c_pointer_move", (DL_FUNC) &arch_c_pointer_move, 2},
  {"arch_c_export_schema", (DL_FUNC) &arch_c_export_schema, 2},
  {"arch_c_export_array_data", (DL_FUNC) &arch_c_export_array_data, 2},
  {"arch_c_allocate_schema", (DL_FUNC) &arch_c_allocate_schema, 0},
  {"arch_c_allocate_array_data", (DL_FUNC) &arch_c_allocate_array_data, 0},
  {"arch_c_allocate_array_stream", (DL_FUNC) &arch_c_allocate_array_stream, 0},
  {"arch_c_schema_xptr_new", (DL_FUNC) &arch_c_schema_xptr_new, 6},
  {"arch_c_schema_deep_copy", (DL_FUNC) &arch_c_schema_deep_copy, 1},
  {"arch_c_schema_data", (DL_FUNC) &arch_c_schema_data, 1},
  {"arch_c_xptr_addr", (DL_FUNC) &arch_c_xptr_addr, 1},
  {NULL, NULL, 0}
};
/* end generated by data-raw/make_callentries.R */

void R_init_arch(DllInfo *dll) {
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);

  // used by external packages linking to internal arch code from C
  R_RegisterCCallable("arch","arch_c_array_from_sexp",(DL_FUNC) &arch_c_array_from_sexp);
  R_RegisterCCallable("arch","arch_c_array_info",(DL_FUNC) &arch_c_array_info);
  R_RegisterCCallable("arch","arch_c_arch_array_stream",(DL_FUNC) &arch_c_arch_array_stream);
  R_RegisterCCallable("arch","arch_c_function_array_stream",(DL_FUNC) &arch_c_function_array_stream);
  R_RegisterCCallable("arch","arch_c_export_array_stream",(DL_FUNC) &arch_c_export_array_stream);
  R_RegisterCCallable("arch","arch_c_arch_array_stream_get_schema", (DL_FUNC) &arch_c_arch_array_stream_get_schema);
  R_RegisterCCallable("arch","arch_c_arch_array_stream_get_next", (DL_FUNC) &arch_c_arch_array_stream_get_next);
  R_RegisterCCallable("arch","arch_c_array_validate", (DL_FUNC) &arch_c_arch_array_stream_get_next);
  R_RegisterCCallable("arch","arch_c_logical_from_bitmask", (DL_FUNC) &arch_c_logical_from_bitmask);
  R_RegisterCCallable("arch","arch_c_bitmask_from_logical", (DL_FUNC) &arch_c_bitmask_from_logical);
  R_RegisterCCallable("arch","arch_c_logical_from_array", (DL_FUNC) &arch_c_logical_from_array);
  R_RegisterCCallable("arch","arch_c_integer_from_array", (DL_FUNC) &arch_c_integer_from_array);
  R_RegisterCCallable("arch","arch_c_double_from_array", (DL_FUNC) &arch_c_double_from_array);
  R_RegisterCCallable("arch","arch_c_raw_from_array", (DL_FUNC) &arch_c_raw_from_array);
  R_RegisterCCallable("arch","arch_c_character_from_array", (DL_FUNC) &arch_c_character_from_array);
  R_RegisterCCallable("arch","arch_c_buffers_from_character", (DL_FUNC) &arch_c_buffers_from_character);
  R_RegisterCCallable("arch","arch_c_deep_copy", (DL_FUNC) &arch_c_deep_copy);
  R_RegisterCCallable("arch","arch_c_double_from_int64", (DL_FUNC) &arch_c_double_from_int64);
  R_RegisterCCallable("arch","arch_c_int64_from_double", (DL_FUNC) &arch_c_int64_from_double);
  R_RegisterCCallable("arch","arch_c_int64_from_integer", (DL_FUNC) &arch_c_int64_from_integer);
  R_RegisterCCallable("arch","arch_c_pointer", (DL_FUNC) &arch_c_pointer);
  R_RegisterCCallable("arch","arch_c_pointer_is_valid", (DL_FUNC) &arch_c_pointer_is_valid);
  R_RegisterCCallable("arch","arch_c_pointer_release", (DL_FUNC) &arch_c_pointer_release);
  R_RegisterCCallable("arch","arch_c_pointer_addr_dbl", (DL_FUNC) &arch_c_pointer_addr_dbl);
  R_RegisterCCallable("arch","arch_c_pointer_addr_chr", (DL_FUNC) &arch_c_pointer_addr_chr);
  R_RegisterCCallable("arch","arch_c_pointer_move", (DL_FUNC) &arch_c_pointer_move);
  R_RegisterCCallable("arch","arch_c_export_schema", (DL_FUNC) &arch_c_export_schema);
  R_RegisterCCallable("arch","arch_c_export_array_data", (DL_FUNC) &arch_c_export_array_data);
  R_RegisterCCallable("arch","arch_c_allocate_schema",(DL_FUNC) &arch_c_allocate_schema);
  R_RegisterCCallable("arch","arch_c_allocate_array_data",(DL_FUNC) &arch_c_allocate_array_data);
  R_RegisterCCallable("arch","arch_c_allocate_array_stream", (DL_FUNC) &arch_c_allocate_array_stream);
  R_RegisterCCallable("arch","arch_c_schema_xptr_new",(DL_FUNC) &arch_c_schema_xptr_new);
  R_RegisterCCallable("arch","arch_c_schema_deep_copy", (DL_FUNC) &arch_c_schema_deep_copy);
  R_RegisterCCallable("arch","arch_c_schema_data", (DL_FUNC) &arch_c_schema_data);
  R_RegisterCCallable("arch","arch_c_xptr_addr", (DL_FUNC) &arch_c_xptr_addr);

}
